victim_1:
    target: 'ruptureit'
    snifferendpoint: 'http://127.0.0.1:9000'
    sourceip: '192.168.1.70'
    realtimeurl: 'http://127.0.0.1:3031'
victim_2:
    target: 'dimkarakostas'
    snifferendpoint: 'http://127.0.0.1:9000'
    sourceip: '192.168.43.246'
    realtimeurl: 'http://127.0.0.1:3031'
